name: my-first-workflow
# To get trigger 
on: push
jobs:
  job1:
   name: JOB1
   runs-on: ubuntu-latest
   steps:
     - name: Running single command in job 1
       run: echo "Hi This is my firest Github workflow"
     - name : checking OS-Release background
       run: cat /etc/os-release 
  job2:
    needs: job1
    name:  JOB02
    runs-on: ubuntu-latest
    steps:
      - name: checking the hostname
        run: hostname
      - name: running multiple commands
        run: 
         echo "Hi from Saurabh Dubey"
         cal 
        
    
