name: my-first-workflow
# To get trigger 
on: 
#push:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:
jobs:
  job1:
   name: JOB1
   runs-on: ubuntu-latest
   steps:
     - name: Running single command in job 1
       run: echo "Hi This is my firest Github workflow"
     - name : checking OS-Release background
       run: cat /etc/os-release 
  job2:
    needs: job1
    name:  JOB02
    runs-on: ubuntu-latest
    steps:
      - name: checking the hostname
        run: hostname
      - name: running multiple commands
        run: 
         echo "Hi from Saurabh Dubey";
         ps -ef;
         df -lk;
         cat /etc/passwd;
  job3:
    needs: job2
    name: JOB03
    runs-on: ubuntu-22.04
    steps:
      - name : small step
        run: sleep 10
  job4:
    needs: job1
    name: JOB04
    runs-on: ubuntu-22.04
    steps:
      - name : small step
        run: sleep 20   
  job5:
   name: checkout repost
   runs-on: ubuntu-latest
   steps:
    - name : checkout step
      uses : actions/checkout@v5.0.0
    - name: check readme file
      run : cat README.md
    
